global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "course-consumer-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["127.0.0.1:8082"]

  - job_name: "course-producer-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["127.0.0.1:8081"]
